### ISSUE TITLE
GOTO Copenhagen

### ISSUE THREAD

**Issue by gangsta** [devopsmalmo/meetups#23]
**1** of 1-day free conference ticket will be given away during our next meetup, make sure you join us!

https://www.meetup.com/DevOpsMalmo/events/265160644/

**1** of 1-day free conference ticket will be given away for the best talk idea.
where to add your talk idea? create and Issue to meetup repository with your talk idea, example DataOps.

https://github.com/devopsmalmo/meetups/issues/new

**1** of 1-day free conference ticket will be given away for people who really want to attend GOTO; CPH, how to detect who really wants to go? please comment below this issue we'll select a winner.

End date for winners is **Nov, 5 2019**.

**Comment by velith** [comment]
I would like to attend Goto

**Comment by chikoo-ankit** [comment]
I would be interested to attend

**Comment by gangsta** [comment]
Cool we have 2 people for available 2 tickets.
/close

**Comment by gangsta** [comment]
@velith and @chikoo-ankit will share Linkedin post about it.
