### ISSUE TITLE
Jenkins X meetup

### ISSUE THREAD

**Issue by gangsta** [devopsmalmo/meetups#29]
We haven't had meetup about Jenkins X,
I assume that's great and trending topic in open source community. More People will be interested.

**Comment by gangsta** [comment]
@kvarak @velith can you guys please check if you have any good network who is good in Jenkins X ?

**Comment by kvarak** [comment]
I have a possible person that can do a Jenkins X meetup. I'll follow it up.

**Comment by gangsta** [comment]
Awesome :+1:  waiting for it.

**Comment by hferentschik** [comment]
Hi there, Hardy here, I am a maintainer of Jenkins X and happy to give a presentation. I am located in Göteborg so travel is easy to sort out :-)

**Comment by gangsta** [comment]
Hi Hardy, thanks for comment , Sounds awesome , I'm looking forward to it,
what about Wednesday 18 March 2020 ?

Waiting for awesome collaboration.

**Comment by gangsta** [comment]
Forgot to mention , probably that will send you notification @hferentschik :+1:

**Comment by hferentschik** [comment]
>  Wednesday 18 March 2020 

Is there an alternative? The 18th is a bit tricky since I have already another meeting that day.

Regarding the topic, what's I talk a bit about things like Git and Chat Ops and how Jenkins X is utilizing these ideas. Of course with a corresponding demo.

**Comment by gangsta** [comment]
You can pick any date as long it's `Monday, Tuesday, Wednesday` this time preference is Wednesday 
between March 16 - April 17.

Topic: sounds amazing , you can already create pull request to Master branch as described in Readme

**Comment by hferentschik** [comment]
What's do you thin about PR #36? 25th of March? What time does the meeting usually start?

**Comment by gangsta** [comment]
You did Great Job!
Our timing is pretty static. 
```
Agenda:
17:30 - 17:45 Meet & Greet
17:45 - 18:30 Introducing Jenkins X
18:30 - 18:50 Pizza&Drinks
18:50 - 19:30 QA/Continue Discussion
```
You can include this into PR :+1: 

Thanks :+1: Looking forward to have awesome evening hosted together :tada:

**Comment by gangsta** [comment]
We can close this issue since we have already talk accepted ,
Good job done here
