### ISSUE TITLE
GOTOcph

### ISSUE THREAD

**Issue by gangsta** [devopsmalmo/meetups#44]
#GOTOcph

**Comment by tndata** [comment]
Join me at #GOTOcph

**Comment by gangsta** [comment]
@tndata easy win! :+1:  you are fast :fast_forward:

**Comment by gangsta** [comment]
@tndata please contact https://twitter.com/DevopsMalmo for free ticket.

**Comment by felix-tran** [comment]
Join me at #GOTOcph

**Comment by gangsta** [comment]
@T-Felix Tore was faster I'm sorry, we can try next time :+1:

**Comment by aleem580** [comment]
Join me at #GOTOcp
